# Generated by Django 3.0.7 on 2022-02-04 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('mensagem', models.CharField(max_length=50)),
                ('de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='de', to=settings.AUTH_USER_MODEL)),
                ('para', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='para', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
