# Generated by Django 3.0.7 on 2022-02-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_questao_questaousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='resposta',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
