# Generated by Django 3.0.7 on 2022-02-13 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_questao_resposta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questao',
            new_name='QuestaoResposta',
        ),
    ]
