# Generated by Django 3.0.7 on 2022-02-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_questaoresposta_owasp'),
    ]

    operations = [
        migrations.AddField(
            model_name='owasp',
            name='descricao',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
