# Generated by Django 3.0.7 on 2022-02-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220213_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owasp',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
