# Generated by Django 3.0.7 on 2022-02-13 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220213_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontuacao',
            options={'ordering': ['pontuacao']},
        ),
    ]
