# Generated by Django 3.0.7 on 2022-02-14 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_textohtml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textohtml',
            name='questao',
        ),
        migrations.AddField(
            model_name='textohtml',
            name='owasp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.OWASP'),
            preserve_default=False,
        ),
    ]
