# Generated by Django 3.0.7 on 2022-02-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220213_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='questaoresposta',
            name='link',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questaoresposta',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
    ]
