# Generated by Django 3.0.7 on 2022-02-18 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_questaoresposta_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questaoresposta',
            name='link',
        ),
    ]
